version: "3.6"

services:
  filman-server:
    container_name: filman-server
    ports:
      - "8000:8000"
    build:
      # context: /FILMAN-SERVER
      context: .
      dockerfile: FILMAN-SERVER/Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql://y168:1B00_3267ae@mysql.mikr.us/db_y168
    restart: unless-stopped

  filman-discord:
    depends_on:
      - filman-server
    container_name: filman-discord
    build:
      # context: /FILMAN-DISCORD
      context: .
      dockerfile: FILMAN-DISCORD/Dockerfile
    environment:
      - DISCORD_TOKEN=MTE4NDUzMTQxMjY2MjEwNDA5NQ.GDmZof.QH06crcIcS3vdiFeH5JhLkkCv-pz2GcccB8360
    restart: unless-stopped

  filman-crawler:
    depends_on:
      - filman-server
    container_name: filman-crawler
    build:
      # context: /FILMAN-CRAWLER
      context: .
      dockerfile: FILMAN-CRAWLER/Dockerfile
    environment:
      - CORE_ENDPOINT=http://filman-server:8000
    restart: unless-stopped