version: "3.6"

services:
  filman-server:
    container_name: filman-server
    ports:
      - "8000:8000"
    build:
      context: /FILMAN-SERVER
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - filman-network

  filman-discord:
    container_name: filman-discord
    build:
      context: /FILMAN-DISCORD
      dockerfile: Dockerfile
    links:
      - "filman-server:filman-discord"
    restart: unless-stopped
    networks:
      - filman-network

networks:
  filman-network:
    driver: bridge

    
  # filman-crawler:
  #   container_name: filman-crawler
  #   build:
  #     context: /FILMAN-CRAWLER
  #     dockerfile: Dockerfile
  #   restart: unless-stopped