volumes:
  mariadb:
    driver: local

networks:
  db:
    driver: bridge

services:
  filman_server:
    container_name: filman_server
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    expose:
      - "8000"
    build:
      context: .
      dockerfile: src/filman_server/Dockerfile

    # bind-mount host source for fast dev reloads
    volumes:
      - ./:/app:delegated

    environment:
      - SQLALCHEMY_DATABASE_URL=mysql://root:root1234@mariadb/filman_dev
      - SENTRY_ENABLED=false
      - SENTRY_DSN=
      - PYTHONPATH=/app/src
      - MIGRATIONS_PATH=/app/migrations
      - ALEMBIC_INI=/app/alembic.ini

    # run uvicorn with --reload so the process restarts on file changes
    command: ["uvicorn", "filman_server.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - db

    restart: unless-stopped

  filman_discord:
    container_name: filman_discord
    depends_on:
      - filman_server
    build:
      context: .
      dockerfile: src/filman_discord/Dockerfile

    # bind-mount host code for live reload
    volumes:
      - ./:/app:delegated

    environment:
      - DISCORD_TOKEN=
      - PYTHONPATH=/app/src

    # use watchmedo to restart the bot process when Python files change
    command: ["watchmedo", "auto-restart", "--patterns=*.py;*.yaml;*.yml", "--recursive", "--", "python3", "-OO", "main.py"]

    networks:
      - db

    restart: unless-stopped

  filman_crawler:
    container_name: filman_crawler
    depends_on:
      - filman_server
    build:
      context: .
      dockerfile: src/filman_crawler/Dockerfile

    # bind-mount host code for live reload
    volumes:
      - ./:/app:delegated

    environment:
      - CORE_ENDPOINT=http://filman_server:8000
      - SENTRY_ENABLED=false
      - SENTRY_DSN=
      - PYTHONPATH=/app/src

    # restart the crawler process on file changes
    command: ["watchmedo", "auto-restart", "--patterns=*.py;*.yaml;*.yml", "--recursive", "--", "python3", "-m", "filman_crawler.main"]

    networks:
      - db

    restart: unless-stopped

  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: root1234
      MYSQL_PASSWORD: root1234
    expose:
        - "40000"
    ports:
        - "40000:3306"
    volumes:
     - mariadb:/var/lib/mysql
    networks:
      - db
              
  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
    networks:
      - db
